apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: owasp-oshp-wasm
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://quay.io/trevorbox/owasp-oshp-wasm:v1
  imagePullPolicy: Always
  phase: AUTHN
  # pluginConfig:
  #   header: "Foggle"
  #   value: "FoggleV"
